### ISSUE TITLE
Fix MIPS2QImage to support RGB16F

### ISSUE THREAD

**Issue by UX3D-wahlster** [ux3d/glTF-Compressonator#7]
QImage *CImageLoader::MIPS2QImage(MipSet *tmpMipSet, int level, CMP_Feedback_Proc pFeedbackProc)

Compressonator\Applications\CompressonatorGUI\Components\cpImageLoader.cpp

**Comment by UX3D-nopper** [comment]
Using the internal XRGB format and converting before usage.
